/**
 * Generate AUTOPILOT.md — the project-level context document that each
 * spawned `claude -p` subprocess reads before implementing.
 *
 * Regenerated by the orchestrator from state.json before EACH implementation
 * spawn (live mode, PR9). Lives at `<repo>/.autopilot/AUTOPILOT.md`.
 *
 * The doc carries the contract that prevents the implementing subprocess from:
 *   - re-implementing already-completed goals
 *   - touching frozen test specs or orchestrator state
 *   - running destructive git commands
 *   - advancing to goals it doesn't own
 *
 * It also gives the subprocess just enough project context (conventions, file
 * layout summary, completed-goal summaries) to make sensible local decisions
 * without needing global awareness.
 */

import type { AutopilotState, Goal } from "./autopilot-state";

export interface DocContext {
  state: AutopilotState;
  userGoalText: string;
  currentGoalId: string | null;        // explicit highlight in doc; null in dry-run
}

export function renderAutopilotDoc(ctx: DocContext): string {
  const { state, userGoalText, currentGoalId } = ctx;
  const total = state.goals.length;
  const done = state.completed.length;
  const failed = state.failed.length;
  const remaining = total - done - failed;

  return `# Autopilot project context

> **You are reading this because you were spawned by the agent-council
> autopilot to implement a single leaf goal. This document is regenerated
> by the orchestrator before each spawn — it reflects the CURRENT state of
> the project, not the state when the project started.**

## The original user goal

\`\`\`
${userGoalText.trim()}
\`\`\`

## Project state (snapshot)

- Started: ${state.started_at}
- Total leaves: ${total}
- Completed: ${done}
- Failed: ${failed}
- Remaining: ${remaining}
- Last green commit: ${state.last_green_commit || "(none yet)"}
- Mode: ${state.live_mode ? "LIVE" : "DRY-RUN"}
${currentGoalId ? `- **Your goal: \`${currentGoalId}\`** — see \`.autopilot/goals/${currentGoalId}.md\`` : ""}

## All leaf goals (status)

${state.goals.map((g) => formatGoalLine(g, currentGoalId)).join("\n")}

## Conventions for this project

- Bun + TypeScript. Tests use \`bun:test\` (\`import { describe, test, expect } from "bun:test"\`).
- Run \`bun test\` to verify. Run \`bun run typecheck\` for types.
- Commit messages: Conventional Commits (\`feat(g3): ...\`, \`fix(g3): ...\`).
- Per-goal scope is enforced by convention; do not touch files outside what
  your goal requires.

## Hard rules (orchestrator-enforced)

These are not suggestions. The orchestrator (or git hooks) will reject
violations and may roll back your commits.

1. **Frozen specs.** Files under \`.council/specs/\` are CONTRACT. Do not
   modify, delete, or rename them. A pre-commit hook (when active in live
   mode) rejects any diff that touches an active goal's spec.
2. **Orchestrator state.** Do not write to \`.autopilot/state.json\`,
   \`.autopilot/control.json\`, or any file the orchestrator owns. Read-only
   from the implementing-session perspective.
3. **Other goals.** Implement exactly the goal listed as \`current_goal_id\`
   in this doc. Do not advance, decompose further, or "fix" other goals.
4. **No destructive git.** Never \`git reset --hard\`, \`git push\`,
   \`git branch -D\`, or rewrite history. The orchestrator handles rollback.
5. **Always commit.** When you make a meaningful change that compiles, commit
   it. Multiple small commits are better than one big one — they let the
   orchestrator detect progress between iterations.

## Done signal

When \`bun run autopilot verify --goal <your-goal-id>\` exits 0, your work is
done. Make a final commit with the title \`feat(<your-goal-id>): <summary>\`
and exit. The orchestrator will pick up the work from there.

## Completed-goal summaries

These goals are already done. Their code is in the repo at the
\`last_green_commit\` referenced above. Don't reimplement them; you may
read their code if it's useful context for your own work.

${formatCompletedSummaries(state.goals, state.completed)}
`;
}

function formatGoalLine(g: Goal, currentGoalId: string | null): string {
  const marker = g.id === currentGoalId ? " ← YOU ARE HERE" : "";
  const statusBadge = ({
    pending: "[ ]",
    in_progress: "[~]",
    needs_review: "[?]",
    done: "[x]",
    failed: "[!]",
  } as const)[g.status];
  return `- ${statusBadge} **${g.id}**: ${g.title}${marker}`;
}

function formatCompletedSummaries(allGoals: Goal[], completedIds: string[]): string {
  if (completedIds.length === 0) return "_(none yet)_";
  const completed = allGoals.filter((g) => completedIds.includes(g.id));
  return completed
    .map(
      (g) => `### ${g.id}: ${g.title}

${g.description}

Implemented in commit: \`${g.green_commit || "(unknown)"}\``
    )
    .join("\n\n");
}
